name: CI

on: [push]

jobs:
  build:
    runs-on:  ubuntu-20.04
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install -r requirements.txt
        pip install -r requirements_qa.txt
    - name: Analysing the code with pylint
      run: |
        export PYTHONPATH=${PYTHONPATH}:$(pwd)
        pylint $(git ls-files '*.py') --rcfile .github/.pylintrc
    - name: Test optimizers
      run: |
        export PYTHONPATH=${PYTHONPATH}:$(pwd)
        pytest tests -v -m optimizers
    - name: Test LKMeans
      run: |
        export PYTHONPATH=${PYTHONPATH}:$(pwd)
        pytest tests -v -m lkmeans
    - name: Test API
      run: |
        export PYTHONPATH=${PYTHONPATH}:$(pwd)
        pytest tests -v -m api -s
