name: CI

on: [push]

jobs:
  build:
    runs-on:  ubuntu-20.04
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install -r requirements.txt
        pip install -r config/requirements_qa.txt

    - name: Analyzing the code with pylint
      run: |
        source config/bootstrap.sh
        pylint lkmeans/ --rcfile config/.pylintrc

    - name: Test optimizers
      run: |
        source config/bootstrap.sh
        pytest lkmeans/tests -v -m optimizers

    - name: Test LKMeans
      run: |
        source config/bootstrap.sh
        pytest lkmeans/tests -v -m lkmeans

    - name: Test API
      run: |
        source config/bootstrap.sh
        pytest lkmeans/tests -v -m api -s

    - name: Test Poetry Build
      run: |
        source config/bootstrap.sh
        bash config/release_build.sh
